### ISSUE TITLE
Remove stripes from Drag and Drop

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#130]
Discuss with Sam, Emma and Kim

**Comment by egrdina** [comment]
[Plain drag and drop.pdf](https://github.com/coralproject/ask/files/501635/Plain.drag.and.drop.pdf)

**Comment by egrdina** [comment]
**Hover interactions**

Regarding hover interactions, in order to signal to users when they can drag and drop and when they can't, when hovering on the question number (aka the drag and drop area) the drag and drop icon (4 arrows) should appear. When hovering on the right-side utility buttons (duplicate, trash, and arrows), a pointer/ hand icon should appear. When hovering on the question text (any area which is not the question number or utility buttons) a normal cursor should appear.
