### ISSUE TITLE
Admin should be able to set their own "Other" text

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#51]
- Instead of button text showing as Other, make this text editable

<img width="670" alt="other_text" src="https://cloud.githubusercontent.com/assets/1077300/17310083/d84c47ba-5807-11e6-8970-7efd9f17c477.png">

**Comment by egrdina** [comment]
"Other:" is editable to admins if they want to add, "Other, please specify:" for example.

"Other" should also have a colon following it so that readers can submit text when they select Other.
![screen shot 2016-08-02 at 11 53 49 am](https://cloud.githubusercontent.com/assets/7856099/17335449/fa572122-58a7-11e6-846a-4e871ea77e45.png)
