### ISSUE TITLE
Clicking anywhere in the gray background bar (not just the form name) on the Forms page should open a form

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#83]
Otherwise, you can't open forms with no Form Name.

<img width="1057" alt="blank_form" src="https://cloud.githubusercontent.com/assets/1077300/18182042/cf3c645c-7053-11e6-9b08-943ca844abd1.png">

**Comment by pablocubico** [comment]
Looks like there is no direct way on `react-mdl` to add a listener to a row, which should be a very simple thing to do. I could write a workaround, maybe using some DOM traversing on a cell event, or something like that, but maybe we should discuss if `react-mdl` is the library to use before it's too late. I already had to send a few patches and had to rollback a commit because of things not working on `react-mdl`, it also lacks customization features. 

For example: this is the table component of the `material-ui` lib.

http://www.material-ui.com/#/components/table

The API looks more coherent, but I don't know the lib in depth, I think Riley had a few concerns about `material-ui`.

Any thoughts? Other libs?

**Comment by pablocubico** [comment]
Putting the "blocked" label just to mark it as "on hold"...

**Comment by okbel** [comment]
I agree. I don't think ```react-md``` is mature enough to fit our needs. Also I ran into some issues too (https://github.com/tleunen/react-mdl/issues/386). I'm looking into ```material ui``` in depth to see if its a good option for us.

**Comment by kgardnr** [comment]
I'm gonna close this for now; we're addressing it more simply here: https://github.com/coralproject/ask/issues/110
